### ISSUE TITLE
race condition in jdbc xdb and foundation

### ISSUE THREAD

**Issue by mhus** [mhus/mhus-sop#6]
java.lang.NullPointerException
	at de.mhus.lib.adb.DbManagerJdbc.getMappingName(DbManagerJdbc.java:1378)
	at de.mhus.lib.adb.DbManagerJdbc.createSqlSelect(DbManagerJdbc.java:164)
	at de.mhus.lib.adb.DbManagerJdbc.getByQualification(DbManagerJdbc.java:156)
	at de.mhus.lib.adb.DbManagerJdbc.getByQualification(DbManagerJdbc.java:126)
	at de.mhus.lib.adb.DbManagerJdbc.getObjectByQualification(DbManagerJdbc.java:108)
	at de.mhus.osgi.sop.foundation.FoundationDbImpl.doPostInitialize(FoundationDbImpl.java:91)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$MyTrackerCustomizer.addingService(SopDbManagerService.java:123)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$MyTrackerCustomizer.addingService(SopDbManagerService.java:105)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$1.run(SopDbManagerService.java:66)
	at de.mhus.lib.core.MThread$Container.run(MThread.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
09:01:04.999 WARN  [MThread de.mhus.osgi.sop.impl.adb.SopDbManagerService$1] (114)[mapping not exist][db.sopacl.target]
09:01:04.999 WARN  [MThread de.mhus.osgi.sop.impl.adb.SopDbManagerService$1] (114)
java.lang.NullPointerException
	at de.mhus.lib.adb.DbManagerJdbc.getMappingName(DbManagerJdbc.java:1378)
	at de.mhus.lib.adb.DbManagerJdbc.createSqlSelect(DbManagerJdbc.java:164)
	at de.mhus.lib.adb.DbManagerJdbc.getByQualification(DbManagerJdbc.java:156)
	at de.mhus.lib.adb.DbManagerJdbc.getByQualification(DbManagerJdbc.java:126)
	at de.mhus.lib.adb.DbManagerJdbc.getObjectByQualification(DbManagerJdbc.java:108)
	at de.mhus.osgi.sop.foundation.FoundationDbImpl.doPostInitialize(FoundationDbImpl.java:100)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$MyTrackerCustomizer.addingService(SopDbManagerService.java:123)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$MyTrackerCustomizer.addingService(SopDbManagerService.java:105)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
	at de.mhus.osgi.sop.impl.adb.SopDbManagerService$1.run(SopDbManagerService.java:66)
	at de.mhus.lib.core.MThread$Container.run(MThread.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
09:01:05.001 INFO  [MThread de.mhus.osgi.sop.impl.adb.SopDbManagerService$1] (114)[disconnect]

**Comment by mhus** [comment]
Fixed in 1.6.3
